### ISSUE TITLE
IQL weight sharing across agents

### ISSUE THREAD

**Issue by irenezhang30** [oxwhirl/pymarl#101]
[Here](https://github.com/oxwhirl/pymarl/blob/73960e11c5a72e7f9c492d36dbfde02016fde05a/src/controllers/basic_controller.py#L29), it looks like the agents are always sharing weights, even for the case of IQL. But in my understanding, in IQL each agent should learn its parameters separately. What am I missing here?

**Comment by hijkzzz** [comment]
Because the shared parameters can improve learning efficiency of NN.
