### ISSUE TITLE
Terminated handling in episode runner

### ISSUE THREAD

**Issue by davidbrandfonbrener** [oxwhirl/pymarl#11]
Line 75 of the episode runner is:
    "terminated": [(terminated != env_info.get("episode_limit", False),)]

I'm not sure what this was meant to do, but it was causing a difficult to find bug for me. Solution was to replace it with:
    "terminated": [(terminated,)]

Let me know if I'm missing something, otherwise can you fix this?

**Comment by tabzraz** [comment]
If the environment has terminated only because the episode limit has been reached (env_info["episode_limit"] is True), then we don't want to treat that transition as a terminal state. 

Line 75 makes sure to store terminated as False for this situation.
