### ISSUE TITLE
Hi,I have a question want to ask?

### ISSUE THREAD

**Issue by BCWang93** [oxwhirl/pymarl#12]
Hello, this is a very good  implement,I want to know, this environment must use docker?If I am not use docker,it can run?Hope you reply!Thanks!Thank you very much!

**Comment by samvelyan** [comment]
Running pymarl with docker is optional. It runs perfectly fine locally as well without docker. Take a look at the following link for details: https://github.com/oxwhirl/pymarl#run-an-experiment.

**Comment by BCWang93** [comment]
> Running pymarl with docker is optional. It runs perfectly fine locally as well without docker. Take a look at the following link for details: https://github.com/oxwhirl/pymarl#run-an-experiment.

Hello,this is a great repo.I want to know how can I use my own algorithm to test in the environment to training?Thank you very much!
