### ISSUE TITLE
Hi, I have this error in running!

### ISSUE THREAD

**Issue by BCWang93** [oxwhirl/pymarl#13]
The error is like this:

'Process Process-3:
Traceback (most recent call last):
  File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/a/COMA/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
    reward, terminated, env_info = env.step(actions)
  File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
    agent_action = self.get_agent_action(a_id, action)
  File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
    "Agent {} cannot perform action {}".format(a_id, action)
AssertionError: Agent 0 cannot perform action 0
'
Can you help me to solve this?Thanks!

**Comment by PaLeroy** [comment]
Hey,
Just got the same error on several runs using COMA.
Were you using COMA too?
However, it never occurred using QMIX algorithms.

**Comment by BCWang93** [comment]
> Hey,
> Just got the same error on several runs using COMA.
> Were you using COMA too?
> However, it never occurred using QMIX algorithms.

yes,I also use the coma.Did you know how to solve this problem?

**Comment by BCWang93** [comment]
> Hey,
> Just got the same error on several runs using COMA.
> Were you using COMA too?
> However, it never occurred using QMIX algorithms.

yes, I also using COMA,Do you know how to solve this problem?

**Comment by PaLeroy** [comment]
I have not investigated yet.
I got this bug "randomly" after 242030, 10046672 and 4677522 transitions.
It seems to be always caused by the action 0 (the no-op action when a unit is dead).
But the exception occurs simply if the selected action is not an available one, not because the unit is not dead...

**Comment by tabzraz** [comment]
Sorry for the late reply. It's unlikely I'll be able to take a look at this issue in the next couple of weeks.

Are you using pytorch version >1? 

If the problem only occurs with COMA, then the code for the parallel_runner is unlikely to be the problem. 

Any unavailable actions should not be chosen by the [action selector](https://github.com/oxwhirl/pymarl/blob/master/src/components/action_selectors.py), but it would be worth checking that is indeed true.

**Comment by BCWang93** [comment]
> Sorry for the late reply. It's unlikely I'll be able to take a look at this issue in the next couple of weeks.
> 
> Are you using pytorch version >1?
> 
> If the problem only occurs with COMA, then the code for the parallel_runner is unlikely to be the problem.
> 
> Any unavailable actions should not be chosen by the [action selector](https://github.com/oxwhirl/pymarl/blob/master/src/components/action_selectors.py), but it would be worth checking that is indeed true.

Hi,thanks for your reply!I am use the pytorch version is >1.I am not test other algorithm recently!But somebody test the qmix algorithm is running normal!

**Comment by BCWang93** [comment]
> Sorry for the late reply. It's unlikely I'll be able to take a look at this issue in the next couple of weeks.
> Are you using pytorch version >1?
> If the problem only occurs with COMA, then the code for the parallel_runner is unlikely to be the problem.
> Any unavailable actions should not be chosen by the action selector, but it would be worth checking that is indeed true.

so,can you solve this problem in recent weeks?Thank you!

**Comment by BCWang93** [comment]
so,can you solve this problem in recent weeks?Thank you! @samvelyan

**Comment by jyericlin** [comment]
Encountered the same issue when running QMIX as well. It occurs when running the following command:
`python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z `

Tested it in two machines, but both have the same issue. I am using PyTorch 0.4.1. I would appreciate if you could provide pointers on how to fix this issue.

**Comment by tabzraz** [comment]
I'll take another look at this issue soon.
When I've been running experiments using the parallel_runner I haven't come across this.

**Comment by tabzraz** [comment]
I haven't been able to reproduce this to debug it.

**Comment by GoingMyWay** [comment]
Same issue with QMIX.

**Comment by OuariachiRafik** [comment]
> Same issue with QMIX. Rarely happens but happened today.
> 
> ```
> AssertionError: Agent 3 cannot perform action 0
> ```

Hello, We got this error today when trying the 10x10, did you figure out how to fix it ?
