### ISSUE TITLE
failed when running an experiment (No mudule named 'smac.env')

### ISSUE THREAD

**Issue by Who-Am-I25** [oxwhirl/pymarl#136]
We didn't build the Dockerfile and directly set up StarCraft II and SMAC by using bash install_sc2.sh. The environment we download includes StartCraftII folder and SMAC_Maps folder.
When we run "python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z", it raises the following error:
ModuleNotFoundError: No mudule named 'smac.env'. What are the correct steps to run codes?

**Comment by theRossFromFriends** [comment]
Try installing smac separately with `pip install git+https://github.com/oxwhirl/smac.git` as it says in their readme https://github.com/oxwhirl/smac

**Comment by samvelyan** [comment]
Seems like smac repo is not properly installed. The instruction above should solve the issue.
