### ISSUE TITLE
1c_3s_5z map?

### ISSUE THREAD

**Issue by saizhang0218** [oxwhirl/pymarl#14]
Hi, I want to evaluate on the 1c_3s_5z map, which is used as a benchmark for the QMIX paper, I can not find it under this directory: smac/smac/env/starcraft2/maps/SMAC_Maps/
Can you upload this map? Or is there any equivalent maps I can use? Thanks!

**Comment by Zymrael** [comment]
I checked the paper and the SMAC docs (https://github.com/oxwhirl/smac/blob/master/docs/smac.md) and there is no 1c_3s_5z map mentioned anywhere.

**Comment by saizhang0218** [comment]
Thanks for reply, I mean the QMIX paper: https://arxiv.org/pdf/1803.11485.pdf   In Figure 3(f), 1c_3s_5z is used as a benchmark to evaluate the QMIX.

**Comment by samvelyan** [comment]
Hi. I've just replied to this same question in the SMAC codebase https://github.com/oxwhirl/smac/issues/7. So closing this one.

**Comment by samvelyan** [comment]
@saizhang0218 I've added 1c3z5z map in the in https://github.com/oxwhirl/smac/commit/c231b7a59c2215b58c985a4a73cb3e6310cbf89f.

**Comment by saizhang0218** [comment]
Thanks!
