### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c apt-get update -y && apt-get install software-properties-common -y &&     add-apt-repository -y multiverse && apt-get update -y && apt-get upgrade -y &&     apt-get install -y apt-utils nano vim man build-essential wget sudo &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by Qungezuishuai** [oxwhirl/pymarl#145]
ERROR: failed to solve: process "/bin/sh -c apt-get update -y && apt-get install software-properties-common -y &&     add-apt-repository -y multiverse && apt-get update -y && apt-get upgrade -y &&     apt-get install -y apt-utils nano vim man build-essential wget sudo &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by samvelyan** [comment]
Please use an appropriate issue title and provide detailed description of the issue you are facing.
