### ISSUE TITLE
cuDNN version in dockerfile is outdated

### ISSUE THREAD

**Issue by KandBM** [oxwhirl/pymarl#148]
This line of the dockerfile references and outdated and unsupported version of cuDNN:
`FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04`
Replacing with the line below seems to work:
`FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu16.04`

**Comment by alsanron** [comment]
Hi, both lines are the same. Did you manage to get it to work with a different one?

**Comment by KandBM** [comment]
I think so, but I've moved on from the project and don't have the file, so I will close the issue.
