### ISSUE TITLE
self. versions = self.get_versions(containing=game_version)   get_versions     containing, sorted(ret.keys())))

### ISSUE THREAD

**Issue by shenglei1** [oxwhirl/pymarl#149]
In the pysc2/run_configs/platforms.py
ValueError: Unknown game version: 4.1.4. Known versions: ['4.6.2', 'latest']

**Comment by oldroad9** [comment]
Could you tell me how to solve this problem?

**Comment by oldroad9** [comment]
I meet this problem too.
