### ISSUE TITLE
Why add agent's previous action to agent's input?

### ISSUE THREAD

**Issue by tolyan3212** [oxwhirl/pymarl#153]
Hello,

In this implementation agents' network is a recurrent network, and this should allow for agents to remember necessary previous actions and observations. But the multi-agent controller also appends to agents' inputs their previous action.

What is the reason for that, and is it really necessary?

Thanks!

**Comment by samvelyan** [comment]
If you are using the SMAC benchmark, there is a special flag for this called `obs_last_action`. See [SMAC code](https://github.com/oxwhirl/smac/blob/32cd6ddbbe4a9ebcd9711894c0043fda0bbfd8aa/smac/env/starcraft2/starcraft2.py#L77) for more details on all flags that specify the observation function.
