### ISSUE TITLE
Cannot reproduce the result using 3s_5z map 

### ISSUE THREAD

**Issue by Kabibi** [oxwhirl/pymarl#17]
Thanks for your repository. 
I am trying to reproduce your results In QMIX paper. I ran the command like this: 
```
python main.py --config=qmix --env-config=sc2 with env_args.map_name=3s5z
```
And this is the result I got using the default parameter setting in `qmix_smac.yaml`. The won rate is almost 0.
![image](https://user-images.githubusercontent.com/11223918/57135044-a9c3f280-6dda-11e9-920e-ba09eb0660a7.png)

However, in QMIX paper, the test win rate achieves nearly 80% after 2.0 million timesteps' training. 
![image](https://user-images.githubusercontent.com/11223918/57135515-3f13b680-6ddc-11e9-8296-f266dea03062.png)

Am I missing something? Thanks :)

**Comment by tabzraz** [comment]
In the QMIX paper, we performed a training step after every episode but for the SMAC results we only do it after 8 episodes. 

If you want to replicate the setup used in the QMIX paper you can do it by setting `batch_size_run=1'.
Or using the episode runner whose config is [here](https://github.com/oxwhirl/pymarl/blob/master/src/config/algs/qmix.yaml).
