### ISSUE TITLE
how can I distinguish different units's observations in the batch?

### ISSUE THREAD

**Issue by Kabibi** [oxwhirl/pymarl#19]
I'm trying to adapt your algorithm under **3s5z** map(3 Stalkers & 5 Zealots). The batch['obs'] is of shape [32, 74, 8, 128].

My questions is how can I distinguish Stalkers' observations from Zealots' observations in batch['obs']? For example, I guess maybe **batch['obs'][:, :, :3]** are Stalkers' observations and **batch['obs'][:, :, 3:]** are Zealots' observations. 

(It seems that Stalkers and Zealots' batch['avail_actions'] are exactly the same, so cannot judge from this.)

Thank You in Advance

**Comment by samvelyan** [comment]
Hi!

There are 8 units overall on this map the order of which is sorted by unit_type id. The observations of i-th agent in this batch are [:, :, i, :], where the first 3 agents are Stalkers, followed by 5 Zealots.

**Comment by BCWang93** [comment]
> Hi!
> 
> There are 8 units overall on this map the order of which is sorted by unit_type id. The observations of i-th agent in this batch are [:, :, i, :], where the first 3 agents are Stalkers, followed by 5 Zealots.

Hi,I have this error in running the COMA algorithm.
The error is like this:

'Process Process-3:
Traceback (most recent call last):
File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/a/COMA/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
reward, terminated, env_info = env.step(actions)
File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
agent_action = self.get_agent_action(a_id, action)
File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
"Agent {} cannot perform action {}".format(a_id, action)
AssertionError: Agent 0 cannot perform action 0
'
Can you help me to solve this?Thanks!
