### ISSUE TITLE
Anyone can run the COMA algorithm code?

### ISSUE THREAD

**Issue by BCWang93** [oxwhirl/pymarl#20]
Anyone can run the coma algorithm normaly?I have this erros like this:
The error is like this:

'Process Process-3:
Traceback (most recent call last):
File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
self._target(*self._args, **self._kwargs)
File "/home/a/COMA/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
reward, terminated, env_info = env.step(actions)
File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
agent_action = self.get_agent_action(a_id, action)
File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
"Agent {} cannot perform action {}".format(a_id, action)
AssertionError: Agent 0 cannot perform action 0
'
Can you help me to solve this?Thanks!

**Comment by esquires** [comment]
I also get this error. It seems to happen rarely (e.g., not until timestep 2 million) but nevertheless it is consistent when I do a training.

Here is the command I am running
```
python3 src/main.py --config=coma_smac --env-config=sc2 with env_args.map_name=2s3z
```

**Comment by GoingMyWay** [comment]
@esquires 

I read your command but got error

```
$ python3 src/main.py --config=coma_smac --env-config=sc2 with env_args.map_name=2s3z                                                                  [21:33:28]
src/main.py:69: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
src/main.py:48: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
[INFO 21:34:17] root Saving to FileStorageObserver in results/sacred.
[DEBUG 21:34:18] pymarl Using capture mode "fd"
[INFO 21:34:18] pymarl Running command 'my_main'
[INFO 21:34:18] pymarl Started run with ID "5"
[DEBUG 21:34:18] pymarl Starting Heartbeat
[DEBUG 21:34:18] my_main Started
[DEBUG 21:34:18] pymarl Stopping Heartbeat
[ERROR 21:34:18] pymarl Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 31, in my_main
    env_args['seed'] = _config["seed"]
sacred.utils.SacredError: The configuration is read-only in a captured function!
```

What is wrong with the code? To be honest I really hate `Sacred`. It makes running the code complex and hard to control.

**Comment by tabzraz** [comment]
@GoingMyWay For the sacred problem are you using the version of sacred in the Dockerfile?
For running Coma, I will take a closer look and add any changes to #13

**Comment by GoingMyWay** [comment]
@tabzraz  I did not use Docker.

**Comment by Gezx** [comment]
> Anyone can run the coma algorithm normaly?I have this erros like this:
> The error is like this:
> 
> 'Process Process-3:
> Traceback (most recent call last):
> File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
> self._target(*self._args, **self._kwargs)
> File "/home/a/COMA/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
> reward, terminated, env_info = env.step(actions)
> File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
> agent_action = self.get_agent_action(a_id, action)
> File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
> "Agent {} cannot perform action {}".format(a_id, action)
> AssertionError: Agent 0 cannot perform action 0
> '
> Can you help me to solve this?Thanks!



> Anyone can run the coma algorithm normaly?I have this erros like this:
> The error is like this:
> 
> 'Process Process-3:
> Traceback (most recent call last):
> File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/home/a/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
> self._target(*self._args, **self._kwargs)
> File "/home/a/COMA/pymarl/src/runners/parallel_runner.py", line 221, in env_worker
> reward, terminated, env_info = env.step(actions)
> File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 373, in step
> agent_action = self.get_agent_action(a_id, action)
> File "/home/a/anaconda3/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 439, in get_agent_action
> "Agent {} cannot perform action {}".format(a_id, action)
> AssertionError: Agent 0 cannot perform action 0
> '
> Can you help me to solve this?Thanks!



> I also get this error. It seems to happen rarely (e.g., not until timestep 2 million) but nevertheless it is consistent when I do a training.
> 
> Here is the command I am running
> 
> ```
> python3 src/main.py --config=coma_smac --env-config=sc2 with env_args.map_name=2s3z
> ```

I met the same prpblem, have you solved it？

**Comment by Gezx** [comment]
@BCWang93 Have you solved this problem, I met the same error.
