### ISSUE TITLE
I have this error in running the qmix algorithm

### ISSUE THREAD

**Issue by LiuQiangOpenMind** [oxwhirl/pymarl#21]
[INFO 16:10:01] root Saving to FileStorageObserver in results/sacred.
[DEBUG 16:10:05] pymarl Using capture mode "fd"
[DEBUG 16:10:06] pymarl Stopping Heartbeat
[ERROR 16:10:06] pymarl Failed after 0:00:01!
Traceback (most recent calls WITHOUT Sacred internals):
  File "D:/PyProjects/pymarl/main.py", line 32, in my_main
    env_args['seed'] = _config["seed"]
sacred.utils.SacredError: The configuration is read-only in a captured function!

**Comment by deeponcology** [comment]
How did you resolve this?

**Comment by DrinkSpriteEveryday** [comment]
I have this problem as well

**Comment by thiagotandrade** [comment]
I've had this same issue and solved it by opening the file `pymarl/src/main.py` and adding the below command under imports:
`SETTINGS['CONFIG']['READ_ONLY_CONFIG'] = False`
