### ISSUE TITLE
running is intercepted with error between StarCraft 2 app

### ISSUE THREAD

**Issue by SungyunPark** [oxwhirl/pymarl#24]
![crash](https://user-images.githubusercontent.com/46016058/62346757-3c874100-b532-11e9-9caf-e44fc89f11e9.PNG)

Hi I tried running qmix with MMM map

(star2) D:\Documents\star2_multi_agents\pymarl-master\pymarl-master\src>python main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=MMM
main.py:71: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
main.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_dict = yaml.load(f)
[INFO 14:27:16] root Saving to FileStorageObserver in results/sacred.
[DEBUG 14:27:19] pymarl Using capture mode "fd"

So this is run now but any unit in sc2 does not move and time is not started just stay in 0:00. And the picture I posted is come up with sc2 app. I live in Korea so in English that does mean "There is an error in access authorization from core". second sentence meant "Please explain the situation when an error occurred to help development team solve the problem". Last one meant "when you are discussing with blizzard about this problem, use below ID". The buttons are respectively "running again", and "close". 

As a result, I clicked "close" button but any unit in sc2 app does not take any action.

**Comment by samvelyan** [comment]
Seems like there could something wrong with your StarCraft II installation. Have you tried [testing thee SMAC package](https://github.com/oxwhirl/smac#testing-smac)? Try running this command:
```bash
$ python -m smac.examples.random_agents
```
