### ISSUE TITLE
questions about observation space

### ISSUE THREAD

**Issue by Jarvis-K** [oxwhirl/pymarl#26]
For 25m map, the observation space is 10xnum_agents. Does not is should be 10 for each agent? If the each agent concatenate the observations around it, what's the order it based on?

**Comment by samvelyan** [comment]
The `get_obs()` function on `25m` map returns a list of 25 observations, one for each agent. The length of the observations vector (for default SMAC parameters) on this map is indeed 250, but that number actually depends on a number of parameters. If you want to get a better sense of why it is 250, you can take a look at the implementation of the `get_obs_size()` function [here](https://github.com/oxwhirl/smac/blob/c231b7a59c2215b58c985a4a73cb3e6310cbf89f/smac/env/starcraft2/starcraft2.py#L999). Feel free to let me know if something is not clear.
