### ISSUE TITLE
fail to build docker image

### ISSUE THREAD

**Issue by YuiiCh** [oxwhirl/pymarl#27]
BREAK when running build.sh, step 23. 

CODE:
    RUN pip3 install git+https://github.com/oxwhirl/smac.git

ERROR:
Successfully built SMAC absl-py future mpyq portpicker s2protocol ordered-set
ERROR: sacred 0.7.2 has requirement jsonpickle<1.0,>=0.7.2, but you'll have jsonpickle 1.2 which is incompatible.
Installing collected packages: future, mpyq, ordered-set, jsonpickle, deepdiff, s2clientprotocol, portpicker, urllib3, certifi, idna, chardet, requests, enum34, websocket-client, sk-video, absl-py, s2protocol, whichcraft, mock, pysc2, SMAC
  Found existing installation: jsonpickle 0.9.6
    Uninstalling jsonpickle-0.9.6:
      Successfully uninstalled jsonpickle-0.9.6
Successfully installed SMAC-0.1.0b1 absl-py-0.8.0 certifi-2019.9.11 chardet-3.0.4 deepdiff-4.0.7 enum34-1.1.6 future-0.17.1 idna-2.8 jsonpickle-1.2 mock-3.0.5 mpyq-0.2.5 ordered-set-3.1.1 portpicker-1.3.1 pysc2-3.0.0 requests-2.22.0 s2clientprotocol-4.10.3.76114.0 s2protocol-4.10.3.76114.0 sk-video-1.1.10 urllib3-1.25.6 websocket-client-0.56.0 whichcraft-0.6.1
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/__init__.py", line 77, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 237, in main
    timeout=min(5, options.timeout)
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/base_command.py", line 108, in _build_session
    index_urls=self._get_index_urls(options),
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 559, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/download.py", line 170, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/utils/misc.py", line 1044, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1974, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1414, in has_metadata
    return self._has(path)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1845, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1722, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1679, in load
    mtime = os.stat(path).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/jsonpickle-0.9.6-py3.5.egg'
The command '/bin/sh -c pip3 install git+https://github.com/oxwhirl/smac.git' returned a non-zero code: 1

**Comment by YuiiCh** [comment]
I guess it's not caused by network interruption.

**Comment by YuiiCh** [comment]
It requires jsonpickle<1.0,>=0.7.2. But it automatically uninstall the existing jsonpickle 0.9.6 and reinstall jsonpickle 1.2.0 which may finally cause the error.

HOW CAN I STOP IT FROM UNINSTALL jsonpickle 0.9.6 ？

**Comment by YuiiCh** [comment]
> It requires jsonpickle<1.0,>=0.7.2. But it automatically uninstall the existing jsonpickle 0.9.6 and reinstall jsonpickle 1.2.0 which may finally cause the error.
> 
> HOW CAN I STOP IT FROM UNINSTALL jsonpickle 0.9.6 ？

or just stop it try to install new jsonpickle....

**Comment by YuiiCh** [comment]
> It requires jsonpickle<1.0,>=0.7.2. But it automatically uninstall the existing jsonpickle 0.9.6 and reinstall jsonpickle 1.2.0 which may finally cause the error.
> 
> HOW CAN I STOP IT FROM UNINSTALL jsonpickle 0.9.6 ？

or just stop it from trying to install new jsonpickle....

**Comment by YuiiCh** [comment]
It requires jsonpickle<1.0,>=0.7.2. But it automatically uninstall the existing jsonpickle 0.9.6 and reinstall jsonpickle 1.2.0 which may finally cause the error.

HOW CAN I STOP IT FROM TRY TO INSTALLING jsonpickle of lastest version？

**Comment by YuiiCh** [comment]
> I guess it's not caused by network interruption.

**Comment by yuan1202** [comment]
hi @YuiiCh 

Have you managed to solve this issue. I am running into this as well.

**Comment by PMatthaei** [comment]
Me too.

**Comment by KCharoenpitaks** [comment]
Me too

**Comment by YuiiCh** [comment]
> hi @YuiiCh
> Have you managed to solve this issue. I am running into this as well.

No. Sorry

**Comment by tabzraz** [comment]
Does it work if you add:
`RUN pip3 install jsonpickle==0.9.6`
before 
`# install Sacred (from OxWhirl fork)`
`RUN pip3 install setuptools`
in the Dockerfile?

**Comment by PMatthaei** [comment]
Worked for me. But i still receive errors when running

**Comment by YuiiCh** [comment]
> Does it work if you add:
> `RUN pip3 install jsonpickle==0.9.6`
> before
> `# install Sacred (from OxWhirl fork)`
> `RUN pip3 install setuptools`
> in the Dockerfile?

Thank you very much! It works.

**Comment by yuan1202** [comment]
it works for me too. Thanks!

**Comment by tabzraz** [comment]
@PMatthaei That looks like a pytorch version error when using version >0.4.

Try replacing lines 73-74 with the following in q_learner.py
`mac_out_detach = mac_out.clone().detach()`
`mac_out_detach[avail_actions == 0] = -9999999`
`cur_max_actions = mac_out_detach[:, 1:].max(dim=3, keepdim=True)[1]`

**Comment by PMatthaei** [comment]
@tabzraz 
As far as I could test your proposed changes, it seems to work. Thanks!!
