### ISSUE TITLE
Running docker in Windows

### ISSUE THREAD

**Issue by PMatthaei** [oxwhirl/pymarl#30]
I try to run pymarl in a docker container on a windows pc. Besides from adjusting the run.sh to:

```
#!/bin/bash
HASH=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 4 | head -n 1)
GPU=$1
name=$(whoami)_pymarl_GPU_${GPU}_${HASH}

echo "Launching container named '${name}' on GPU '${GPU}'"
# Launches a docker container using our image, and runs the provided command

if hash nvidia-docker 2>/dev/null; then
  cmd=nvidia-docker
else
  cmd=docker
fi

NV_GPU="$GPU" ${cmd} run \
    --name $name \
    --user $(id -u):$(id -g) \
    -v /$(pwd):/pymarl \
    -t pymarl:1.0 \
    ${@:2}
```
I receive an error from OpenGL

> Attempting to initialize EGL from file libEGL.so ...
> Failed to find EGL functions in library file!

 on execution of command:

> [INFO 18:15:22] absl Launching SC2: /pymarl/3rdparty/StarCraftII/Versions/Base69232/SC2_x64 -listen 127.0.0.1 -port 15923 -dataDir /pymarl/3rdparty/StarCraftII/ -tempDir /tmp/sc-and62dp2/ -eglpath libEGL.so

I am not very familiar with docker but it looks like the docker image is missing support for headless opengl rendering which does not cause problems on Ubuntu16.04 systems.
Am i doing somethin wrong is there indeed no support for windows in the current image?

PS: could using this dockerfile as a base help: https://hub.docker.com/r/nvidia/cudagl ?

**Comment by tbomonfils** [comment]
I got it working. I executed the file from inside the Docker without any change.

**Comment by tabzraz** [comment]
We haven't tested the dockerfile/code on Windows. 

This looks to be a StarCraft 2 issue, but I don't have a nice way to debug/fix it sorry!
