### ISSUE TITLE
When i running the first command in the README , it comes an error.

### ISSUE THREAD

**Issue by lml519** [oxwhirl/pymarl#32]
when i run the command "python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z".The output is that 

[ERROR 20:41:53] pymarl Failed after 0:00:00!
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 31, in my_main
    env_args['seed'] = _config["seed"]
sacred.utils.SacredError: The configuration is read-only in a captured function!

**Comment by samvelyan** [comment]
Solved in https://github.com/oxwhirl/pymarl/commit/9be8cb078ffd05b55a2ee02842ed0ad4a3f28827.
