### ISSUE TITLE
I have some questions when i want to save replay

### ISSUE THREAD

**Issue by lml519** [oxwhirl/pymarl#35]
> python3 src/main.py --config=coma_smac --env-config=sc2 with env_args.map_name=2s3z checkpoint_path=results/models/coma_smac__2019-10-20_11-23-08/ save_replay=True 

when i run this cammand , there is no XXX.replay in my direction in StarCraft2. How can i fix it?

**Comment by samvelyan** [comment]
`save_replay` will only work if the `checkpoint_path` is provided. However, the you can have access to the SMAC environment through `pymarl` and can call its `save_replay()` function wherever needed.

**Comment by lml519** [comment]
did u mean that i should write the direction of module in config. yaml in checkpoint. rather than in this command? another question is the meaning of the checkpoint_path. I want to know the
 direction should be the dorection of
module which has been saved or the direction the replay where I want XXX. replay to occur? thank u for ur reply.

**Comment by samvelyan** [comment]
Oh, sorry. I didn't notice that you provided the `checkpoint_path` in your command.
Did you check the `Replay` directory inside the of StarCraft II folder? If you are using Mac, it's probably `/Applications/StarCraft II/Replays`. On Linux, the StarCraft II directory is the folder you extracted the linux package into.

**Comment by lml519** [comment]
I run this command on Ubuntu16.04. I checked the replay directory in SC2. There is no file in it when i run the command and end with "Thread joined Exiting script". I dont know how to fix it.

**Comment by PMatthaei** [comment]
I think you might have missed adding `runner=episode` at some point.

**Comment by IngyN** [comment]
Hi, I'm having a similar issue on Ubuntu 18.04. The code doesn't seem to give me any errors but I don't find any replay files. I specify save_replay = True and it seems to be loading the checkpoint correctly, I also have the runner=episode from the default. I suppose the replay file should be in: `pymarl/3rdparty/StarCraftII/Replays`.

Here are the contents of the .yml file for the pymarl options and logging options. 
`
# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 20 # Number of episodes to test for
test_interval: 2000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 2000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: True # Log results to tensorboard
save_model: False # Save the models to disk
save_model_interval: 2000000 # Save models after this many timesteps
checkpoint_path: "/home/ingy/Developer/pymarl/results/models/coma__2020-05-08_12-31-56" # Load a checkpoint from this path
evaluate: True # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: True # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results
`
Here is the command I am using: `python3 src/main.py --config=coma --env-config=sc2 with env_args.map_name=2s3z`
