### ISSUE TITLE
I don't find the implementation of the IQL

### ISSUE THREAD

**Issue by sxwgit** [oxwhirl/pymarl#39]
Hello，Thank you for your efforts for this implementations.
I want to find the implementation of the IQL, unfortunately，I don't find it.(but I find the iql_smac.yaml file in config folder) Would you mind tell me where is it?
Thank you!

**Comment by kasimte** [comment]
Are you looking for the `q_learner` file?

https://github.com/oxwhirl/pymarl/blob/master/src/learners/q_learner.py

With IQL, the mixer is set to None.

**Comment by sxwgit** [comment]
@kasimte  Thinks for your answer.
But I get this error 

> ValueError: Mixer None not recognised

using this command 

>  python3 src/main.py --config=iql --env-config=sc2 with env_args.map_name=2s3z

**Comment by kasimte** [comment]
Good point. I've reproduced your error and here is the full traceback:

```
Traceback (most recent calls WITHOUT Sacred internals):
  File "src/main.py", line 35, in my_main
    run(_run, config, _log)
  File "/Users/Kasim/Projects/ml/pymarl/src/run.py", line 48, in run
    run_sequential(args=args, logger=logger)
  File "/Users/Kasim/Projects/ml/pymarl/src/run.py", line 114, in run_sequential
    learner = le_REGISTRY[args.learner](mac, buffer.scheme, logger, args)
  File "/Users/Kasim/Projects/ml/pymarl/src/learners/q_learner.py", line 26, in __init__
    raise ValueError("Mixer {} not recognised.".format(args.mixer))
ValueError: Mixer None not recognised.
```

**Comment by kasimte** [comment]
I suggest trying removing the "None" in the config file like so:

https://github.com/kasimte/pymarl/pull/1/commits/fa6f1c87249c5339b9c818106c9d09830ea90cd3

And then running it again.

**Comment by sxwgit** [comment]
It works. Thanks for your replay.

**Comment by tabzraz** [comment]
Just merged in a fix for this (https://github.com/oxwhirl/pymarl/pull/41), so it should be fixed in the main repo now (Same fix as suggested by kasimte).

I accidentally set the mixer to None instead of leaving it blank in the yaml file when doing the latest updates.
