### ISSUE TITLE
How to save a replay in training?

### ISSUE THREAD

**Issue by cumttang** [oxwhirl/pymarl#4]
I have tried the command like this:

python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=8m checkpoint_path=results/models/qmix_smac_parallel__2019-02-22_06-59-24/ save_replay=True test_nepisode=1

However, there is not any replay in any directory. Is there mistake I did? Please help notice.

**Comment by cumttang** [comment]
Fix it with episode_runner.

**Comment by Kabibi** [comment]
> Fix it with episode_runner.

I also encounter the same issue, could you give more details?

**Comment by samvelyan** [comment]
Simply set `runner=episode` alongside other flags. I'll update this in the README file.
