### ISSUE TITLE
If I want to save replay, that means I must install all on windows?And I want to know which one is client.Thank you.

### ISSUE THREAD

**Issue by Gezx** [oxwhirl/pymarl#42]

**Comment by kasimte** [comment]
You can save a replay on any OS if you have pymarl setup correctly. I have done so successfully on Linux and MacOS. But to actually watch the replay, you'll need to install Starcraft II on Mac or Windows. 

From the README:

> Note: Replays cannot be watched using the Linux version of StarCraft II. Please use either the Mac or Windows version of the StarCraft II client.

Presumably, the client refers to the actual Starcraft II game software.

**Comment by Gezx** [comment]
OK, when I save a replay, I run "python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z checkpoint_path=/home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/ runner=episode t_max=22350", I can't find the replay in StarCraftII/Replays.

there is:
(base) gezhixin@gezhixin-virtual-machine:~/pymarl-master$ python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z checkpoint_path=/home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/ runner=episode
[INFO 14:32:29] root Saving to FileStorageObserver in results/sacred.
[DEBUG 14:32:29] pymarl Using capture mode "fd"
[INFO 14:32:29] pymarl Running command 'my_main'
[INFO 14:32:29] pymarl Started run with ID "18"
[DEBUG 14:32:29] pymarl Starting Heartbeat
[DEBUG 14:32:29] my_main Started
[WARNING 14:32:29] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
[INFO 14:32:29] my_main Experiment Parameters:
[INFO 14:32:29] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'rnn',
    'agent_output_type': 'q',
    'batch_size': 32,
    'batch_size_run': 1,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '/home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/',
    'critic_lr': 0.0005,
    'double_q': True,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'map_name': '2s3z',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 792093572,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'hypernet_layers': 2,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'episode',
    'runner_log_interval': 10000,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_replay': False,
    'seed': 792093572,
    't_max': 2050000,
    'target_update_interval': 200,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'use_cuda': False,
    'use_tensorboard': False}

[INFO 14:32:30] my_main Loading model from /home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/12269
[INFO 14:32:30] my_main Beginning training for 2050000 timesteps
[INFO 14:32:30] absl Launching SC2: /home/gezhixin/pymarl-master/3rdparty/StarCraftII/Versions/Base55958/SC2_x64 -listen 127.0.0.1 -port 23543 -dataDir /home/gezhixin/pymarl-master/3rdparty/StarCraftII/ -tempDir /tmp/sc-bu1kzblo/ -eglpath libEGL.so
[INFO 14:32:30] absl Connecting to: ws://127.0.0.1:23543/sc2api, attempt: 0, running: True
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/gezhixin/pymarl-master/3rdparty/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 23543 -dataDir /home/gezhixin/pymarl-master/3rdparty/StarCraftII/ -tempDir /tmp/sc-bu1kzblo/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
[INFO 14:32:31] absl Connecting to: ws://127.0.0.1:23543/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:23543 (23543)
Startup Phase 3 complete. Ready for commands.
[INFO 14:32:32] absl Connecting to: ws://127.0.0.1:23543/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
[INFO 14:32:36] my_main t_env: 12328 / 2050000
[INFO 14:32:36] my_main Estimated time left: 9 minutes, 39 seconds. Time passed: 6 seconds
[INFO 14:33:20] my_main Recent Stats | t_env:      12328 | Episode:        1
battle_won_mean:           0.0000       ep_length_mean:           59.0000       epsilon:                   0.7669       return_mean:               6.0246
return_std:                0.0000       test_battle_won_mean:      0.0000       test_ep_length_mean:     116.7812       test_return_mean:          9.1181
test_return_std:           2.4998       
[INFO 14:35:51] my_main t_env: 22350 / 2050000
[INFO 14:35:51] my_main Estimated time left: 10 hours, 58 minutes, 12 seconds. Time passed: 3 minutes, 21 seconds
[INFO 14:36:08] my_main Recent Stats | t_env:      22350 | Episode:      195
battle_won_mean:           0.0000       ep_length_mean:           55.3299       epsilon:                   0.5763       grad_norm:                 3.8514
loss:                      0.3740       q_taken_mean:              0.0788       return_mean:               6.6308       return_std:                0.8738
target_mean:               0.1833       td_error_abs:              0.5314       test_battle_won_mean:      0.0000       test_ep_length_mean:     108.6875
test_return_mean:          9.0237       test_return_std:           2.8786       
[INFO 14:36:14] my_main Updated target network
^C[DEBUG 14:36:24] pymarl Stopping Heartbeat
[WARNING 14:36:24] pymarl Aborted after 0:03:55!
Traceback (most recent call last):
  File "src/main.py", line 98, in <module>
    ex.run_commandline(params)
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/sacred/experiment.py", line 318, in run_commandline
    options=args,
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "src/main.py", line 35, in my_main
    run(_run, config, _log)
  File "/home/gezhixin/pymarl-master/src/run.py", line 48, in run
    run_sequential(args=args, logger=logger)
  File "/home/gezhixin/pymarl-master/src/run.py", line 179, in run_sequential
    learner.train(episode_sample, runner.t_env, episode)
  File "/home/gezhixin/pymarl-master/src/learners/q_learner.py", line 101, in train
    loss.backward()
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
KeyboardInterrupt
[INFO 14:36:24] absl Shutdown gracefully.
[INFO 14:36:24] absl Shutdown with return code: -2
(base) gezhixin@gezhixin-virtual-machine:~/pymarl-master$ python3 src/main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z checkpoint_path=/home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/ runner=episode t_max=22350
[INFO 14:36:34] root Saving to FileStorageObserver in results/sacred.
[DEBUG 14:36:34] pymarl Using capture mode "fd"
[INFO 14:36:34] pymarl Running command 'my_main'
[INFO 14:36:34] pymarl Started run with ID "19"
[DEBUG 14:36:34] pymarl Starting Heartbeat
[DEBUG 14:36:34] my_main Started
[WARNING 14:36:34] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
[INFO 14:36:34] my_main Experiment Parameters:
[INFO 14:36:34] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'rnn',
    'agent_output_type': 'q',
    'batch_size': 32,
    'batch_size_run': 1,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '/home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/',
    'critic_lr': 0.0005,
    'double_q': True,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'map_name': '2s3z',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 499089426,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'hypernet_layers': 2,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'runner': 'episode',
    'runner_log_interval': 10000,
    'save_model': False,
    'save_model_interval': 2000000,
    'save_replay': False,
    'seed': 499089426,
    't_max': 22350,
    'target_update_interval': 200,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'use_cuda': False,
    'use_tensorboard': False}

[INFO 14:36:34] my_main Loading model from /home/gezhixin/pymarl-master/results/models/qmix__2019-12-06_20-08-04/12269
[INFO 14:36:34] my_main Beginning training for 22350 timesteps
[INFO 14:36:34] absl Launching SC2: /home/gezhixin/pymarl-master/3rdparty/StarCraftII/Versions/Base55958/SC2_x64 -listen 127.0.0.1 -port 23112 -dataDir /home/gezhixin/pymarl-master/3rdparty/StarCraftII/ -tempDir /tmp/sc-w6h9r0ia/ -eglpath libEGL.so
[INFO 14:36:34] absl Connecting to: ws://127.0.0.1:23112/sc2api, attempt: 0, running: True
Version: B55958 (SC2.3.16)
Build: Jul 31 2017 13:19:41
Command Line: '"/home/gezhixin/pymarl-master/3rdparty/StarCraftII/Versions/Base55958/SC2_x64" -listen 127.0.0.1 -port 23112 -dataDir /home/gezhixin/pymarl-master/3rdparty/StarCraftII/ -tempDir /tmp/sc-w6h9r0ia/ -eglpath libEGL.so'
Starting up...
Startup Phase 1 complete
[INFO 14:36:35] absl Connecting to: ws://127.0.0.1:23112/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:23112 (23112)
Startup Phase 3 complete. Ready for commands.
[INFO 14:36:36] absl Connecting to: ws://127.0.0.1:23112/sc2api, attempt: 2, running: True
Requesting to join a single player game
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface disabled
Configure: score interface disabled
Configure: render interface disabled
Entering load game phase.
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Game has started.
Sending ResponseJoinGame
[INFO 14:36:40] my_main t_env: 12316 / 22350
[INFO 14:36:40] my_main Estimated time left: 2 seconds. Time passed: 6 seconds
[INFO 14:37:24] my_main Recent Stats | t_env:      12316 | Episode:        1
battle_won_mean:           0.0000       ep_length_mean:           47.0000       epsilon:                   0.7669       return_mean:               8.1408
return_std:                0.0000       test_battle_won_mean:      0.0000       test_ep_length_mean:     116.0938       test_return_mean:          8.9379
test_return_std:           3.0949       
[INFO 14:40:04] my_main t_env: 22416 / 22350
[INFO 14:40:04] my_main Estimated time left: -. Time passed: 3 minutes, 29 seconds
[INFO 14:40:22] my_main Recent Stats | t_env:      22416 | Episode:      176
battle_won_mean:           0.0000       ep_length_mean:           52.3571       epsilon:                   0.5764       grad_norm:                 1.8303
loss:                      0.1236       q_taken_mean:              0.0810       return_mean:               7.9365       return_std:                0.9273
target_mean:               0.0304       td_error_abs:              0.2938       test_battle_won_mean:      0.0000       test_ep_length_mean:     113.0156
test_return_mean:          9.0065       test_return_std:           2.9287       
RequestQuit command received.
Closing Application...
unable to parse websocket frame.
[INFO 14:40:23] absl Shutdown gracefully.
[INFO 14:40:23] absl Shutdown with return code: -15
[INFO 14:40:23] my_main Finished Training
Exiting Main
Stopping all threads
Thread Thread-1 is alive! Is daemon: False
Thread joined
Exiting script

**Comment by Gezx** [comment]
I'm sorry, I found the replay.Thank you for your help.

**Comment by mattam301** [comment]
@

> I'm sorry, I found the replay.Thank you for your help.

Can you help me find the replay file? I encountered the similar issue
