### ISSUE TITLE
how can I debug the code,there is the problem

### ISSUE THREAD

**Issue by Gezx** [oxwhirl/pymarl#43]
I debug it by pycharm, and I put the parameters "--config=qmix --env-config=sc2 with env_args.map_name=2s3z save_model=True save_model_interval=20000" in Edit Configurations.
there is:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gezhixin/pymarl-master/src/3rdparty/StarCraftII/Versions'
I know the path is false, but how can I fix it.

**Comment by hxx1996** [comment]
I also meet this problem. how did you fixed?

**Comment by hieunq95** [comment]
> I debug it by pycharm, and I put the parameters "--config=qmix --env-config=sc2 with env_args.map_name=2s3z save_model=True save_model_interval=20000" in Edit Configurations.
> there is:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/gezhixin/pymarl-master/src/3rdparty/StarCraftII/Versions'
> I know the path is false, but how can I fix it.

I got the same problem. How did you solve it?

**Comment by Gezx** [comment]
> > I debug it by pycharm, and I put the parameters "--config=qmix --env-config=sc2 with env_args.map_name=2s3z save_model=True save_model_interval=20000" in Edit Configurations.
> > there is:
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/gezhixin/pymarl-master/src/3rdparty/StarCraftII/Versions'
> > I know the path is false, but how can I fix it.
> 
> I got the same problem. How did you solve it?

You should copy the  " 3rdparty" into the  src directory.

**Comment by Gezx** [comment]
> I also meet this problem. how did you fixed?

You should copy the  " 3rdparty" into the  src directory.

**Comment by hieunq95** [comment]
> > > I debug it by pycharm, and I put the parameters "--config=qmix --env-config=sc2 with env_args.map_name=2s3z save_model=True save_model_interval=20000" in Edit Configurations.
> > > there is:
> > > FileNotFoundError: [Errno 2] No such file or directory: '/home/gezhixin/pymarl-master/src/3rdparty/StarCraftII/Versions'
> > > I know the path is false, but how can I fix it.
> > 
> > 
> > I got the same problem. How did you solve it?
> 
> You should copy the " 3rdparty" into the src directory.

Thank you, problem solved!

**Comment by yangqingsong-victor** [comment]
You can also replace 
`os.environ.setdefault("SC2PATH", os.path.join(os.getcwd(), "3rdparty", "StarCraftII"))`
with 
`os.environ.setdefault("~/StarCraftII", os.path.join(os.getcwd(), "3rdparty", "StarCraftII"))`
 in "src/envs/__init__.py", if your platform is Linux. The "~/StarCraftII" is path of your StarCraftII environment.
