### ISSUE TITLE
How do you develop with this repository?

### ISSUE THREAD

**Issue by PMatthaei** [oxwhirl/pymarl#45]
Hi, 

I am new to developing rl algorithms and ml in general. I wanted to ask here what setup/work pipeline do you use to develop new algorithms for this repo?

I have a hard time to set up pycharm with a miniconda environment and running my code is docker is tedious to find errors.

I am glad for any tip.

**Comment by tabzraz** [comment]
I use a python3 virtualenv and pycharm when developing locally. It can be a little fiddly to get all the dependencies right sometimes though, so that's why we recommend using docker.

**Comment by PMatthaei** [comment]
Hi. Thanks for your reply. Yeah the dependency errors are what drove me to this question. I cant get them running. Is there a way to share your virtualenv setup with me or the community? Just in terms of package versions.

**Comment by tabzraz** [comment]
Running `pip list` on my current venv gives:
```
Package            Version       
------------------ --------------
absl-py            0.2.2         
astor              0.8.0         
bleach             1.5.0         
certifi            2019.3.9      
chardet            3.0.4         
cloudpickle        1.1.1         
cycler             0.10.0        
deepdiff           4.0.7         
docopt             0.6.2         
enum34             1.1.6         
future             0.16.0        
futures            3.1.1         
gast               0.2.0         
grpcio             1.12.0        
html5lib           1.0.1         
idna               2.8           
imageio            2.5.0         
jsonpickle         1.2           
kiwisolver         1.0.1         
Markdown           3.1.1         
matplotlib         2.2.2         
mock               2.0.0         
mpyq               0.2.5         
munch              2.3.2         
mypy               0.720         
mypy-extensions    0.4.1         
numpy              1.16.4        
ordered-set        3.1.1         
pandas             0.24.2        
patsy              0.5.0         
pbr                4.0.3         
Pillow             6.0.0         
pip                19.1.1        
pkg-resources      0.0.0         
portpicker         1.2.0         
protobuf           3.5.2.post1   
py-cpuinfo         5.0.0         
pybind11           2.2.3         
pygame             1.9.6         
pymongo            3.6.1         
pyparsing          2.2.0         
PySC2              3.0.0         
python-dateutil    2.7.2         
pytz               2018.4        
PyYAML             5.1           
requests           2.22.0        
ruamel.yaml        0.15.37       
s2clientprotocol   4.10.3.76114.0
s2protocol         4.10.3.76114.0
sacred             0.7.4         
scipy              1.3.0         
seaborn            0.8.1         
setuptools         41.0.1        
six                1.11.0        
sk-video           1.1.10        
SMAC               0.1.0b1       
snakeviz           0.4.2         
statsmodels        0.9.0         
tensorboard-logger 0.1.0         
termcolor          1.1.0         
torch              1.3.1         
tornado            5.0.2         
typed-ast          1.4.0         
typing-extensions  3.7.4         
urllib3            1.25.3        
webencodings       0.5.1         
websocket-client   0.48.0        
Werkzeug           0.14.1        
wheel              0.33.4        
whichcraft         0.5.2         
wrapt              1.10.11
```

Some of these are probably not relevant.
I'd recomend starting from a scratch installation and installing the relevant components one-by-one (try running the code and installing any packages it complains about).

**Comment by BupyeongHealer** [comment]
Hello! I had a hard time setup pymarl in Windows.
But, Nowadays I can use it by reinstalling some packages. 

` OS : Windows10, virtual env, (not using docker)`

**So, I share my solutions!**
I installed some packages using github clone instead of pip install. 

1. sacred
Uninstall your current sacred, and use this way!
> git clone https://github.com/IDSIA/sacred.git
> cd sacred
> python setup.py install
 
2. jsonpickle
Uninstall your current jsonpickle, and use this way!
> git clone https://github.com/jsonpickle/jsonpickle.git
> cd jsonpickle
> python setup.py develop

Thanks for Pymarl.
