### ISSUE TITLE
How are the Agents called?

### ISSUE THREAD

**Issue by GJHall** [oxwhirl/pymarl#48]
I am trying to understand the training process.

I can see that the Qmixer is called in the q_learning module.

What I cannot see is how the agents (RNNagent) are being called and how they are connected to the hyper network for weight sharing.  

Edit: also, how are the def forward() functions working and what are the REGISTRY functions used for? I believe these are related to the agent in the basic_controller.py module.

**Comment by tabzraz** [comment]
The agents are called through the mac (multi-agent controller):
https://github.com/oxwhirl/pymarl/blob/29ac1a2db8a9174dac1462bace5e800538f48313/src/learners/q_learner.py#L47-L51

The relevant agent outputs are then fed into the mixing network to produce Q_tot.

forward is used in the controller to get the outputs of the agents.

The REGISTRY functions are used to select between different things (controllers, learners, agents, action selectors, etc), so we can change different components easily by just changing a parameter.

**Comment by GJHall** [comment]
Awesome. Thank you.
