### ISSUE TITLE
Had problem running your code

### ISSUE THREAD

**Issue by JianyuSu** [oxwhirl/pymarl#49]
I am new to docker and I failed to run your experiments.
OS: Ubuntu 18.04
Arch: x86_64

standard_init_linux.go:211: exec user process caused "exec format error" is the error I got when I tried to run the code posted in README.m file.

Can you tell me what is the problem if you have any ideas? Thank you.

**Comment by PMatthaei** [comment]
Did you run it with sudo?

**Comment by Mohan-Zhang-u** [comment]
I'm having exactly the same error when executing the command 
`sudo bash run.sh 0 python3 src/main.py --config=noisemix_episode --env-config=sc2 with env_args.map_name=3s5z`
with a newly assigned docker environment. Is there any possible solution to this issue? Thanks in advance!

**Comment by tabzraz** [comment]
Are you able to launch the docker container interactively?

**Comment by AchrafMoussaid** [comment]
> I am new to docker and I failed to run your experiments.
> OS: Ubuntu 18.04
> Arch: x86_64
> 
> standard_init_linux.go:211: exec user process caused "exec format error" is the error I got when I tried to run the code posted in README.m file.
> 
> Can you tell me what is the problem if you have any ideas? Thank you.

Hi JianyuSU, 
did you finally launch the code?

**Comment by JianyuSu** [comment]
Yes, I did! Thank you for your advice.

**Comment by lcassano** [comment]
Hi JianyuSu I have the same problem. How did you solve the issue?

Thanks
