### ISSUE TITLE
Failed to run code

### ISSUE THREAD

**Issue by xxd819240366** [oxwhirl/pymarl#53]
File "/home/xxx/anaconda3/envs/LIIR/lib/python3.6/site-packages/smac/env/starcraft2/starcraft2.py", line 292, in _launch
    self._run_config = run_configs.get(version=self.game_version)
TypeError: get() got an unexpected keyword argument 'version'
TypeError: get() got an unexpected keyword argument 'version'
TypeError: get() got an unexpected keyword argument 'version'

**Comment by samvelyan** [comment]
Are you using the latest version of [PySC2](https://github.com/deepmind/pysc2) on the `master` branch?

**Comment by xxd819240366** [comment]
No,I'm using pysc2==2.0.2

**Comment by samvelyan** [comment]
SMAC [requires](https://github.com/oxwhirl/smac/blob/e5d60341bb98dbdc2a4916f900bbd905342609fa/setup.py#L41) that you use pysc2>=3.0.0. Please update it!

**Comment by xxd819240366** [comment]
Should  I use the latest version of PySC2 ？Such as 3.0?

**Comment by xxd819240366** [comment]
OK,thanks,I'll try.
