### ISSUE TITLE
What is the role of the "fill" and "mask" related variables in the code?

### ISSUE THREAD

**Issue by xxd819240366** [oxwhirl/pymarl#55]

**Comment by tabzraz** [comment]
batch["filled"] tells you if the data at that spot in the batch is real data (from the environment) or a dummy value (padding).
Since we don't want to train on dummy data, we use compute a 'mask' to zero out the contribution of those entries to the loss.

**Comment by xxd819240366** [comment]
Thank you for your reply. I will continue to study the code.

**Comment by xxd819240366** [comment]
The dummy value means if the game ended early but the length of data in the batch is fixed,so code will padding the data to get the same length?

**Comment by tabzraz** [comment]
> The dummy value means if the game ended early but the length of data in the batch is fixed,so code will padding the data to get the same length?

Yeah, thats right. In practise there will be quite a lot of padding since the length of the data is fixed at the maximum possible episode length.
