### ISSUE TITLE
Ubuntu freezes at QMIX 25m

### ISSUE THREAD

**Issue by PMatthaei** [oxwhirl/pymarl#56]
Hi,

I tested COMA 3m, 8m and 25m as well as QMIX 3m and 8m without problems. Only QMIX 25m is giving me a freeze. htop is showing no hardware bottlenecks before the freeze. Has anyone experienced the same? I am using the docker run method.

 Is my setup (16GB RAM, RTX 2070) too weak?

Thanks for the help in advance.

**Comment by tabzraz** [comment]
25m with a buffer of 5k episode will use quite a lot of ram (more than 16gb I think).

**Comment by tmhm** [comment]
More swap could been help.
likes,
```zsh
sudo mkdir swap && cd swap
sudo dd if=/dev/zero of=swapfile bs=1M count=10240
sudo mkswap swapfile
sudo swapon swapfile
free -h
```
