### ISSUE TITLE
If anyone use AMD cpu?I don't know whether I can use AMD CPU for this. And I use rtx2070super.

### ISSUE THREAD

**Issue by Gezx** [oxwhirl/pymarl#59]

**Comment by PMatthaei** [comment]
I also tried running on AMD CPU but receive an error due to hardware incompatibility. I cant remember what it was but I guess some ML python libraries can not run on AMD CPUs.

**Comment by Gezx** [comment]
Thank you. And which AMD CPUs you use, Ryzen or Ryzen2. Have you solve this problem? It will very bad if I can't use AMD CPUs, because I have bought r5 3600x.

**Comment by PMatthaei** [comment]
haha mine was an AMD A8 Series A8-7600...so maybe that was the problem too. I just realized that if you are running your experiments on a GPU it might make no difference which CPU you are using since it is an nvidia GPU. But maybe wait for an answer of someone more familiar with this topic.

**Comment by Gezx** [comment]
Thank you very much. I will try it.
