### ISSUE TITLE
Hi,I have a question want to you help!

### ISSUE THREAD

**Issue by BCWang93** [oxwhirl/pymarl#6]
Hi,I have needed the 'COMA' algorighm implementation recently,I want to know do you have the 'COMA' implementation?Can you help me? Thanks!

**Comment by tabzraz** [comment]
Hi, pymarl has a COMA implementation you can use.

COMA can be run by setting the config parameter `--config=coma_smac` (this will use the hyperparameters we used for the SMAC experiments).
