### ISSUE TITLE
How does PyMARL take actions and make observations in SC2?

### ISSUE THREAD

**Issue by GJHall** [oxwhirl/pymarl#63]
I have reviewed PySC2, sc2clientproto, SMAC, and PyMARL.

I understand that both PySC2 and SMAC use sc2clientproto to make observations and issue commands in SC2.

What I don't understand is how PyMARL is issuing commands within SC2. I don't see SMAC imported any where in PyMARL. The only commonality between the two I see is shared nested MultiAgentEnv from multiagentevn.py.

smac/starcraft2.py
class StarCraft2Env(MultiAgentEnv):

Can you please explain how PyMARL is able to issue commands and gain observations from the SC2 environment using SMAC?

**Comment by Greg-Farquhar** [comment]
The sc2 env class is registered here:
https://github.com/oxwhirl/pymarl/blob/master/src/envs/__init__.py
from which the env is initialised here: https://github.com/oxwhirl/pymarl/blob/e9beece44ffa52203adaf126859b331d80fe1131/src/runners/episode_runner.py#L15

Then observations and actions are sent through the MultiAgentEnv API (e.g. env.get_obs(), etc.)

**Comment by GJHall** [comment]
Thanks Greg!

In the future I should check all the __init__.py  files...
