### ISSUE TITLE
ValueError: Map 'SMAC_Maps/2s3z.SC2Map' not found.

### ISSUE THREAD

**Issue by AchrafMoussaid** [oxwhirl/pymarl#64]
Hi,
I got this error when I'm trying to run an experiment using **_python3 main.py --config=qmix --env-config=sc2 with env_args.map_name=2s3z_**
While my maps are located in SMAC_Maps file 
Can you Help me Please
<img width="938" alt="gi" src="https://user-images.githubusercontent.com/31735009/84570265-4994d380-ad84-11ea-8a6a-ff664e7e6066.PNG">
<img width="836" alt="git" src="https://user-images.githubusercontent.com/31735009/84570267-4d285a80-ad84-11ea-9943-36b9c93d5fe0.PNG">

**Comment by samvelyan** [comment]
Closing this one as the same issues is raised here: https://github.com/oxwhirl/smac/issues/44
