### ISSUE TITLE
Do you plan to implement MADDPG?

### ISSUE THREAD

**Issue by Ankur-Deka** [oxwhirl/pymarl#65]

**Comment by samvelyan** [comment]
There are currently no plans on including the MADDPG implementation in PyMARL. Note that it can be found at https://github.com/openai/maddpg.

**Comment by samvelyan** [comment]
P.S. @Ankur-Deka if you're interested in adding the implementation of MADDPG in PyMARL yourself, we'd be more than happy to assist you and answer your questions.

Cheers
