### ISSUE TITLE
Heterogeneous envs support

### ISSUE THREAD

**Issue by GoingMyWay** [oxwhirl/pymarl#66]
Hi, for heterogeneous envs for example `3s5z_vs_3s6z`, I think we should write an individual agent for both `s` and `z`, any suggestions?

**Comment by samvelyan** [comment]
What do you mean by `writing an individual agent`?

**Comment by GoingMyWay** [comment]
> What do you mean by `writing an individual agent`?

Hi, I mean define individual agents for different type of agents. I saw this assumption, https://github.com/oxwhirl/pymarl/blob/master/src/controllers/basic_controller.py#L78
