### ISSUE TITLE
Training QMIX model on another environment?

### ISSUE THREAD

**Issue by nfitch3** [oxwhirl/pymarl#76]
Is there a way I can use your QMIX implementation to train a model on a different environment? For simplicity assume the generic `env` variable has the same functions/attributes, etc as SMAC. I'm more interested to know if this is possible by running a few lines of code to make the necessary imports to have a QMIX model to train right out of the box.

**Comment by samvelyan** [comment]
Yes. If you provide the implementation of a concrete class that derives from the `MultiAgentEnv` (from [here](https://github.com/oxwhirl/smac/blob/master/smac/env/multiagentenv.py)), similar to how [StarCraft2Env](https://github.com/oxwhirl/smac/blob/master/smac/env/starcraft2/starcraft2.py#L60) does it, you can use QMIX out of the box.

**Comment by nfitch3** [comment]
@samvelyan that's great, thanks!

I noticed the episode `runner` [here](https://github.com/oxwhirl/pymarl/blob/e633fdf50c08a27a8ed43ffc69c7156bc44b5024/src/runners/episode_runner.py) sets the env variable. So after implementing a `MultiAgentEnv` class would I then just need to adjust the file [here](https://github.com/oxwhirl/pymarl/blob/e633fdf50c08a27a8ed43ffc69c7156bc44b5024/src/envs/__init__.py) and specifically add a line like the following?:

`REGISTRY["my_env_name"] = partial(env_fn, env=MultiAgentEnv)`

Is there anything else to change?

**Comment by samvelyan** [comment]
> I noticed the episode runner here sets the env variable. So after implementing a MultiAgentEnv class would I then just need to adjust the file here and specifically add a line like the following?:

Yes!

> Is there anything else to change?

If you're making no changes to the algorithms or networks, than no additional changes are required.
