### ISSUE TITLE
Test learned policy against computer?

### ISSUE THREAD

**Issue by tsliu331** [oxwhirl/pymarl#79]
After training, how would one go about retrieving the agents' policies from a model and playing against the computer AI to evaluate team performance?

**Comment by samvelyan** [comment]
You can save the models by setting `save_model = True` when running the experiments. Learnt models can later be loaded using the `checkpoint_path` parameter. If you only want to execute testing episodes (with no learning), then also set `evaluate=True`. This will execute `test_nepisode` episodes and quit.

**Comment by tsliu331** [comment]
Thanks, @samvelyan. Is it also possible to evaluate two trained models playing against each other?

**Comment by samvelyan** [comment]
Unfortunately, we don't have that functionality in SMAC.
