### ISSUE TITLE
standard_init_linux.go:207: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by youngdlin** [oxwhirl/pymarl#9]
When running an experiment with Docker (`bash run.sh $GPU python3 src/main.py --config=qmix_smac --env-config=sc2 with env_args.map_name=2s3z`) I get the following issue:
`standard_init_linux.go:207: exec user process caused "exec format error".`

Any idea on what might be causing the issue? Thanks!

**Comment by Greg-Farquhar** [comment]
Could maybe be an issue with the shell? Try just './run.sh' instead of 'bash run.sh'
If that doesn't work, are you able to just launch the docker container with './run_interactive.sh' ? Just checking that it's a Docker problem and not related to pymarl specifically.

**Comment by lcassano** [comment]
Hi youngdlin, I have the same issue. Were you able to solve it?

Thanks
