### ISSUE TITLE
Has anyone encountered the problem that QMIX performs very poorly on 3s5z map and 2s3z map?

### ISSUE THREAD

**Issue by Judylalala** [oxwhirl/pymarl#92]
I got a very poor performance on 3s5z map which has 0 win rate all the time. And the win rate on 2s3z is not 0 but very poorly. 
Is it a parameter setting problem?

**Comment by samvelyan** [comment]
What is the exact command you ran?

**Comment by dreamgrave** [comment]
I ran Qmix on 3s5z and 2s3z for 2,000,000 steps last week. The results are quite good. But I discovered Qmix performence is bad for the scenario 3s5z in the experiment section of 1 or 2 papers. It confused me as well.

**Comment by Judylalala** [comment]
> What is the exact command you ran?

Parameters: --config=qmix_beta --env-config=sc2_beta with env_args.map_name=3s5z

**Comment by dreamgrave** [comment]
I ran with --config=qmix

**Comment by dreamgrave** [comment]
> > What is the exact command you ran?
> 
> Parameters: --config=qmix_beta --env-config=sc2_beta with env_args.map_name=3s5z

I found this in the pymarl Readme.md:
**"The previous config files used for the SMAC Beta have the suffix _beta."** 

Starcraft II in SMAC has two version: 4.6 and 4.10. The poor performance may be caused by the version.

**Comment by Judylalala** [comment]
> > > What is the exact command you ran?
> > 
> > 
> > Parameters: --config=qmix_beta --env-config=sc2_beta with env_args.map_name=3s5z
> 
> I found this in the pymarl Readme.md:
> **"The previous config files used for the SMAC Beta have the suffix _beta."**
> 
> Starcraft II in SMAC has two version: 4.6 and 4.10. The poor performance may be caused by the version.

That's really useful information. I did change something with the game version and maybe that's why it didn't perform well. Thanks a lot.
