### ISSUE TITLE
SC2 screen message during training

### ISSUE THREAD

**Issue by Massar88** [oxwhirl/pymarl#94]
Hi, 
Can you please let me know how to get rid of or delete the message (CHEAT local player KillUnitTagBy..) that appears on the game screen during the training?
With many thanks
![SC2 message](https://user-images.githubusercontent.com/79666658/109338644-c1783080-7823-11eb-8a20-10700e6efc68.JPG)

**Comment by samvelyan** [comment]
Deleting due to duplicate issue https://github.com/oxwhirl/pymarl/issues/94
