### ISSUE TITLE
problem of cuda  in the Docker container 

### ISSUE THREAD

**Issue by FanScy** [oxwhirl/pymarl#97]
Hi,
I followed the installation instructions of docker and successfully run the code in the cpu in the docker container.
But **it will get stuck when I used the GPU**. I have installed the  Nvidia-docker and can output the status of `nvidia-smi`.
`torch.cuda.is_available()` is True in the container. 
I have found when I used the cuda() of pytorch it will get stuck.

> root@8c30d63fb526:/pymarl# nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Tue_Jun_12_23:07:04_CDT_2018
> Cuda compilation tools, release 9.2, V9.2.148

It will get stuck when using the cuda() and no error.
> root@8c30d63fb526:/pymarl# python3   
> Python 3.5.2 (default, Jan 26 2021, 13:30:48) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy as np
> >>> import torch 
> >>> torch.cuda.is_available()
> True
> >>> a = np.random.randint(0,10,[3,3])
> >>> a = torch.tensor(a)
> >>> a = a.cuda()
>

**Comment by ThyrixYang** [comment]
Hi, @FanScy 
How did you solve this problem?
