### ISSUE TITLE
updating batch after episode is terminated

### ISSUE THREAD

**Issue by irenezhang30** [oxwhirl/pymarl#99]
In episode_runner.py, why are we still selecting one more action + updating the batch with it after the episode is terminated? https://github.com/oxwhirl/pymarl/blob/73960e11c5a72e7f9c492d36dbfde02016fde05a/src/runners/episode_runner.py#L89

```
        last_data = {
            "state": [self.env.get_state()],
            "avail_actions": [self.env.get_avail_actions()],
            "obs": [self.env.get_obs()]
        }
        self.batch.update(last_data, ts=self.t)

        # Select actions in the last stored state
        actions = self.mac.select_actions(self.batch, t_ep=self.t, t_env=self.t_env, test_mode=test_mode)
        self.batch.update({"actions": actions}, ts=self.t)

```

**Comment by tabzraz** [comment]
The environment terminating doesn't necessarily mean the final state is a terminal state (it might terminate after reaching some pre-defined limit on the length of an episode for example). 
We can then use the information about which actions the agents would have taken in that non-terminal state depending on the algorithm. e.g. in SARSA we can use that final state as a bootstrapping target if we know the joint-action that would be taken.
